### ISSUE TITLE
Simulating the Interfrequency Delay

### ISSUE THREAD

**Issue by srveale** [firasm/CEST#36]
The simulation now runs through the saturation pulse, allows the system to relax for some time defined by adjustable sequence parameters with a hard flip here and there, and uses the resulting magnetization state as the initial state for the next saturation frequency.

Here I simulated alternating frequencies to try and replicate the double-peak phenomenon we've observed in phantoms. There is only one simulated species to the left of the water peak; the peak on the right is an artifact of residual saturation from the previous frequency. It dissappears if the inter-frequency time is long enough, about 5000 - 70000 ms (in excellent agreement with phantom studies... almost too excellent). 

Also note the shoulders on either side of the spectrum as the system approaches a steady state. 

(Forgot to say that the legend gives the interfreq delay for each spectrum)

![double peak disappearing](https://cloud.githubusercontent.com/assets/7737922/7736194/faa88aa0-fef6-11e4-9a2a-00afba5e0500.png)

Some parameters:
B0 = 7.0 T (easy upgrade!)
B1 = 1.0e-6 
saturation pulse duration = 500 ms
there is one 20 degree flip in the sequence

M0a = 1000.0
M0b = M0ax1e-3x10 (so 10mM, used a high concentration for easily cest effect)
T1a = 2.0 # seconds
T2a = 0.6
T1b = 1.0
T2b = 0.2
kb = 40.
ka = M0b/M0a*kb #Transfer rate of pool a to pool b, s^-1. We want a-->b = b-->a
accFactor = 1 (more on this later)

**Comment by srveale** [comment]
Just updating this issue with the latest version of the sim. It agrees with the experience we've had where the mirror peak, established to be a result of alternating frequency offsets, disappears with inter-frequency delay of 6-7 seconds. This is apart from the unreasonable T1 of 4.0 s that I just threw in there.

![response of mirror peak height to ifdelay](https://cloud.githubusercontent.com/assets/7737922/8093446/f74a64ca-0f75-11e5-85d1-49cb42d28403.png)

**Comment by firasm** [comment]
Cool, that's interesting to see. It never actually goes to 0 eh ? that's what we saw in #22 as well, even at 10s, it didn't fully disappear. 

P.S. I don't actually think that 4s is that unreasonable of a T1. Our tumour T1s are between 2s and 3s so @srveale could you add a 3s one as well for reference ?

Other than that, this issue seems to be resolved and addressed. @DrSAR can we close this one and #22 ?

**Comment by srveale** [comment]
In the sim they do go to zero, I just shifted the scale down to see what was happening. The graph is updated with T1 = 3.0 s and I reset the axes to be sure.

**Comment by firasm** [comment]
Okay, much better. I'll close this issue then.
