### ISSUE TITLE
Troubles in the Transverse Plane

### ISSUE THREAD

**Issue by srveale** [firasm/CEST#37]
To walk through this, the first step is looking at the magnetization of each component of each pool in time. The first, third, and fifth plots are the x,y, and z components for the water pool. They oscillate at a frequency proportional to B1; as the saturation pulse rotates M from the z-direction, the y signal increases and so on.

![each component vs time](https://cloud.githubusercontent.com/assets/7737922/7753490/9ffd19dc-ff9a-11e4-8b5f-da95837686a7.png)

The oscillating xy-signal looks like this.

![xy signal vs time](https://cloud.githubusercontent.com/assets/7737922/7753675/d5557308-ff9b-11e4-8fdc-711423a4774c.png)

Because it is oscillating, it is hard to define it's magnitude. If I just say it is the magnitude at some point in time, I could stop the saturation at a minimum or a maximum or in between, leading to inconsistencies when I apply the imaging sequence. Here is what a z-spectrum looks like with this method:

![xy z-spectrum](https://cloud.githubusercontent.com/assets/7737922/7753743/5c831ff6-ff9c-11e4-9283-a230a2349cdc.png)

Not good.

An alternative could be to define the xy-signal as the height of the envelope, which should solve the problem but I'm not sure if that's an accurate representation of reality.

**Comment by srveale** [comment]
@DrSAR and I got to the bottom of this yesterday. The integrator we were using had sampling frequency issues. Building and using the simplest integrator possible enabled the production of this graph:

![image](https://cloud.githubusercontent.com/assets/7737922/7898684/a02f76c4-06bc-11e5-8f60-2c14005ff97c.png)

This is what we are looking for. Unfortunately, this graph took an hour to make. I will start producing graphs to show the dependencies on inter-frequency delay and B1, but I think this issue has been resolved.

**Comment by firasm** [comment]
So we can't use any other integrator period? I'm assuming it took an hour because of your integrator - is that correct? Ultimately I'm wondering if every full simulation experiment take an hour to run?

Also can you comment on How much of our old simulation work will we need to revisit?

**Comment by firasm** [comment]
P.S. Nice work solving the issue!

**Comment by srveale** [comment]
Yes, it took a long time because of the rudimentary integrator. I'm going to upgrade it to an RK4 method and that should bring the time down, but I'm now wary of using pre-built integrators with adaptive step size because I think that is the source of this problem.

**Comment by DrSAR** [comment]
You will have to chose a step-size for RK4 (or any other integrator) and 
somehow avoid the trap that the stock algorithm fell into. Good work and 
I hope this can be sped up in the fullness of time.
S
