### ISSUE TITLE
check out CEST simulator by Craig Jones et al.

### ISSUE THREAD

**Issue by DrSAR** [firasm/CEST#38]
housed here:
http://godzilla.kennedykrieger.org/

The data processing tools might also be useful but are written in MatLab. Might work in octave (the open-source pendant to this)

**Comment by DrSAR** [comment]
@srveale , this might give data that's comparable with your output(s)

**Comment by srveale** [comment]
So after hammering out a few bugs that aren't worth talking about (email for notes if you're interested), I'm ready to compare my sim to theirs. Theirs is on top and mine is on bottom.

![comparison sidebyside](https://cloud.githubusercontent.com/assets/7737922/7971189/d0e42ce0-09f7-11e5-9636-58e92a6b3ab6.jpg)



I made all the parameters equal when I could.
Saturation pulse length: 0.5 seconds
Saturation pulse magnitude: 1.0 uT
B0 = 7 T
Water: T1 = 2s, T2 = 0.6 s, concentration = 1000 au
Solute: T1 = 1s, T2 = 0.2s, concentration = 10 au, chemical shift = 3.6ppm,

Overall they are quite similar. One difference I noticed is that, for their sim, it's not true that the exchanges are equal both ways. ie, ka != kb (kws =! ksw in their notation). In my sim I force the rates to be equal. I'm wondering if this is the right thing to do.

**Comment by srveale** [comment]
With a finer resolution, their sim looks like the same phenomenon I was encountering last week:

![nirbhay jagged](https://cloud.githubusercontent.com/assets/7737922/7971310/b29b111c-09f8-11e5-91cf-bd7ea04c457d.jpg)

If it's the same, my guess is they are only simulating one spin.

**Comment by DrSAR** [comment]
that's funny. I wonder whether we should ask them about this figure...

**Comment by firasm** [comment]
@DrSAR Let's do it - We can corner someone from that group at the CESToronto oral session tomorrow. 




@srveale - that was fast, awesome. Can you point me to a notebook and cell number where I can see the generation of the plot above ? I'd like to look at the notebook and understand it before talking to them.

**Comment by srveale** [comment]
CEST/simulation/Stress Testing CEST Sequence (the original copy)

The plot is towards the bottom, cell 101, but all the different function definitions are in that notebook.

Just in case, these are the values I used on their website to produce the jagged lines:
Saturation pulse length: 0.5 seconds
Saturation pulse magnitude: 1.0 uT
B0 = 7 T
Water: T1 = 2s, T2 = 0.6 s, concentration = 1000 au
Solute: T1 = 1s, T2 = 0.2s, concentration = 10 au, chemical shift = 3.6ppm
number of frequencies: 201

It looks like the spectrum smooths out with longer saturation time, eg 4 seconds, just like mine did last week.

**Comment by firasm** [comment]
Wait what? The spectrum improves with a longer saturation pulse length? 
Did I miss that result on github somehow? Can you point me to it?

That's precisely what we were going to get you to try in the mouse brain tomorrow. There are a couple of ways to increase sat time, so we were going to try both of them and see if we can recover our in vivo peaks. @DrSAR and @andrew, should we have a quick conversation about things to try tomorrow in the brain?

**Comment by srveale** [comment]
These are only using the C Jones simulation:

![nirhaby satlength point5](https://cloud.githubusercontent.com/assets/7737922/7972593/a5027acc-0a02-11e5-992d-0e96416a99f6.jpg)

![nirhbhay satlength 4](https://cloud.githubusercontent.com/assets/7737922/7972609/bb37f16e-0a02-11e5-80c1-cdf3b8bc5241.jpg)

**Comment by DrSAR** [comment]
I'm available tomorrow morning. Plenary is on fetal and placental 
imaging which underwhelms me. So we should talk then. That's still 
before BC awakens and we'll be in time for CESToronto at 10:30. Any takers?

**Comment by firasm** [comment]
Sounds good to me.




Let's meet outside the plenary hall between 9:15-9:30

**Comment by andrewcyung** [comment]
Ok I'll be there

On Jun 3, 2015, at 9:17 PM, "firasm" <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds good to me.




Let's meet outside the plenary hall between 9:15-9:30

**Comment by firasm** [comment]
Going to close this issue, let's use this simulator as a sanity check for our results.

Firas
