### ISSUE TITLE
CEST Spectrum from Andrew's Brain scan on May 29th

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#39]
@andrewcyung  did a CEST brain scan of a mouse before coming so I thought I'd try and visualize it so we can make sense of it

These data are normalized to the 300 ppm freq. offset so they should be comparable to each other.

Here are andrew's notes on the experiment:

```Objectives
repeat successful mouse brain CEST experiment where I got amide/amine peaks
duplicate successful experiment with turboCEST sequence method
investigate the effect of acceleration factor, with respect to total saturation time over the course of an entire image acquisition for one particular offset

** Data Key **
2,3,4: RARE localizers
5,6: fieldmap and shim voxel
9. quick 3-offset CEST scan to characterize B0 homogeneity
10. reproduce successful experiment with ubcCEST_FLASH (1.0 uT, 72x72, 3.6cm FOV, 490 ms sat pulse, TR=500 ms (i.e. ~10 ms imaging time), -1 to 5 ppm with 0.4 ppm stepsize,
11. try to reproduce same thing but with turboCEST acceleration factor 1 (this time, TR has new meaning; does not include sat pulse.  So TR=10ms)
12. same turboCEST sequence but now with 8 sec of inter-experiment delay (between  frequency offset images)
13. now try #12 but with acceleration factor 2
15. acceleration factor of 1, but saturation pulse length is cut in half.   Therefore, time is same as #13 (accel factor 2) and will be about the same saturation duration from start of scan to centre of k-space
16. same as #15 but sat pulse length is 350 ms (narrow range)
17. same as 15 but reverse encoding so that centre of k-space is acquired last
18. repeat of 12 but with narrower frequency range
19. repeat of 18 but accel = 2
20. repeat of 18 but accel = 4
21. repeat of 18 but accel = 8
22. repeat of 12 but narrower frequency range
```

For 1 pixel (blue star)

![unknown](https://cloud.githubusercontent.com/assets/2507459/7951725/247439e2-0979-11e5-9eb1-f578182c5c0e.png)

![unknown-1](https://cloud.githubusercontent.com/assets/2507459/7951734/2e2e512a-0979-11e5-80b3-4e1ee92d562e.png)

**Comment by DrSAR** [comment]
Are we all agreed there is a peak at 3.5ppm? If so, why is it most visible for #20 with acc factor 4?

**Comment by DrSAR** [comment]
wait, the central line of k-space (is it line 35 or 36), when is it acquired in relation to the saturation pulse and in relation to the whole train of pulses?

**Comment by andrewcyung** [comment]
ignore all scans from expno 18 and onwards.  That's when the mouse started moving around.  Scan 20 images can clearly see the mouse moving in the slice direction.  The central line of k-space was acquired for the most part using the standard sequential order, but I did include one reverse centric encoding version.

If I can figure out how to attach a pdf, I can show you the individual datasets overlaid onto the same plot.

**Comment by andrewcyung** [comment]
Some data that I processed that shows spectra from different pixels…
