### ISSUE TITLE
Another potential fix for small scale oscillations without changing iterators. 

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#40]
@DrSAR mentioned to Michael McMahon the oscillation issue that we also see in his simulation. 

He knew about it and suggested that it's because the saturation pulse duration isn't long enough and the "phase gets screwy".

@srveale, when you have a chance, can you switch the integrator back to something fast, make sure you can still see the oscillations, and then run another iteration JUST changing the pulse length to 4seconds. 

This fixed this in his simulation and it should for us as well. 

Firas

**Comment by DrSAR** [comment]
hm, not convinced. this might be a different issue...

**Comment by srveale** [comment]
I'm working on reproducing this. But are these oscillations seen in real life? If our simulator doesn't reflect reality at our most commonly used saturation time, what good is it?

From what I remember, the cause of the wiggles in the simulator were a result of simulating exactly one spin, and not accounting for the spread in frequencies found in a voxel. Averaging over the period - effectively averaging over all the different phases - gets rid of the wiggles and gives a better representation of what is actually happening (as far as I understand it).

**Comment by firasm** [comment]
Michael McMahon claims that yes they do exist in real life in phantoms, but @DrSAR is highly skeptical of this. 




His explanation wasn't very convincing, but given that two independent simulations produced the same result, I'm suspicious if this is an accident

**Comment by srveale** [comment]
I've reproduced the oscillations, and they do indeed vanish with high saturation time.

![satlength point5 wiggles](https://cloud.githubusercontent.com/assets/7737922/7995933/f116b5fe-0acf-11e5-94f1-05e7e9ff354b.png)

![satlength 4 no wiggles](https://cloud.githubusercontent.com/assets/7737922/7995934/f92452ec-0acf-11e5-9322-7c72679dfb2e.png)


I just noticed that the longer saturation time produces a smaller peak, opposite to what I would expect. Maybe something to do with relaxation during the pulse? Anyways, the oscillations disappear, or at least they are visibly smoothed out.

**Comment by DrSAR** [comment]
You can probably test your relaxation hypothesis by modifying the relaxation time of the metabolite

**Comment by srveale** [comment]
I did just that. Multiplying T1 and T2 of the metabolite both by 3 gives :

![satlength 4 long t1](https://cloud.githubusercontent.com/assets/7737922/7998763/efec23be-0af5-11e5-91a8-786e5305d2dc.png)

A bigger peak. So for very long relaxation times, or for short saturation pulses, the magnetization doesn't recover as much between frequency offsets.

**Comment by DrSAR** [comment]
nice.

btw, I am starting to think there might be something to those oscillations. They might even be observable. Here is an interesting publication that rounds out one of the talks in today's CEST session: 
Magnetic Resonance in Medicine, March, 2013. 10.1002/mrm.24284
A new method for detecting exchanging amide protons using chemical exchange rotation transfer
Zhongliang Zu, Vaibhav A. Janve, Junzhong Xu, Mark D. Does, John C. Gore, Daniel F. Gochberg

This might be an option for slow exchanging species. It would require setting up a pulse train rather than CW saturation (and new simulation questions...)

**Comment by firasm** [comment]
Okay, thanks Scott. 

So to summarize :

- Oscillations may manifest in real life as well, we just haven't come across the right combination of exchange rates and imaging parameters. 
- Oscillations can be smoothed away by increasing the saturation pulse length (or averaging multiple spins, or moving away from adaptive step-size integrators [this is the one I understand the least and is least intutitive])
- A Longer saturation pulse may result in a smaller peak, depending on the relaxation times of the species you're looking at .

So for now, we should keep the fast integrator and remove oscillations with a longer saturation time. 

If someone is interested in exploring the oscillations further, they should open another issue with that question.
