### ISSUE TITLE
Mouse Brain - Long Saturation Pulse (4s), Accelerated (72x) spectra

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#41]
mouse study name: 'cest_FM.w01'

This is the result from today's brain experiment that Barry and @srveale did for us. @DrSAR, @andrewcyung, and I got some ideas on things to try from some people we've talked to and we were impatient so we thought we'd get started.

What we mean by accelerating of 72x, is that for 72 phase encodes, only one saturation pulse was used. The "delay" in the plot below refers to the waiting time between subsequent saturation pulses (in this case, equivalent to subsequent frequency offsets).

This is still the first mouse, the second mouse is currently being imaged.

![unknown-2](https://cloud.githubusercontent.com/assets/2507459/7995349/09b42372-0ae3-11e5-8918-41e33a505492.png)

For reference, here is the CEST spectrum for the non-accelerated scan (one sat pulse per k-space line) with a 4s pulse length. I've actually shown two reference datasets, one with a low FA (5) and one with a high FA (80) to demonstrate the importance of SNR in the CEST Spectrum. You'll notice that the images look comparable but in reality aren't and the spectra show the noise

![unknown-3](https://cloud.githubusercontent.com/assets/2507459/7995643/efc29496-0ae5-11e5-8e8d-cf744ebf72a2.png)

The main questions this poses/solves:

1. InterSaturationFreq Delay doesn't seem to matter, so we will likely ditch it.
1. Long Pulse length seems to result in CEST peaks around 3.5 ppm
1. Outstanding question is: how many peaks are there!?
1. It *does* seem to make a difference whether you do linear offsets or alternating offsets, but the question is which one is the correct one to do? The linear offsets results in 3 (!) discernible peaks around 3.5 ppm whereas the alternating offsets results in a single (maybe 2?) broad peak
1. If you have a long sat pulse (4s) before each k-space line, your CEST signal disappear!? Why !?!?

The plot thickens...

**Comment by DrSAR** [comment]
Why do you say, the CEST signal disappears for long sat pulses (4s). I presume I am to look at the CEST-no acc-high FA(80) panel? I think there is still a peak there, no?

**Comment by andrewcyung** [comment]
Hi guys, here are the cest spectra WITHOUT normalization:

[cid:image001.png@01D09EFA.F40ED610]
You can see that the signal range is so, so much wider for FA=80 degrees as opposed to FA=5 degrees.  I noticed that the 5 degree flip angle has an attenuator value of 39.5 dB.  Could we be in the range where the digital resolution of the attenuation is insufficient to give us the proper flip angle?  It’s a gauss pulse which has some of the lowest peak amplitudes.

**Comment by andrewcyung** [comment]
The elevated noise that we are seeing from expno 17 onwards in this recent experiment is predominantly motion ghosting – looking through the images confirms this.  Seems like lately we’re having terrible problems with keeping the animal still (brain was majorly displaced three times over the course of the experiment).

If we do this again, I would suggest:


-          Change to hermite pulse so that transmit attenuations for excitation can be lower values

-          Pay attention to restricting motion

-          Change readout direction to A-P to reduce motion ghosting
