### ISSUE TITLE
EPI CEST - analyzing the Peaks in a rat brain

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#46]
Here's a single voxel and the resulting CEST spectrum:

![cest](https://cloud.githubusercontent.com/assets/2507459/8269724/ed380cf2-1769-11e5-9b68-c57e22e913e8.png)

I see a few peaks: 3ppm, 2.2ppm, 
I will be trying to average a few more pixels together to see if I can improve the peaks, and then trying to fit multiple lorentzians to it.

Perhaps @piotrkoz, @DrSAR, or @andrewcyung can comment on whether I should select the whole tumour as an roi and average over it (after shifting the water peak to 0) or get someone to outline a sub-region in the tumour corresponding to a brain region.

I will update this page a I do more work on this... @DrSAR: perhaps you could give some direction on what you're looking for in the talk?

**Comment by DrSAR** [comment]
What would be nice is a tumour averaged spectrum although the SNR looks pretty good already. I doubt the contrast will improve.

The other thing would be a map of this peak. The simplest might be fits of three humps: the water, the broad line and the peak of interest.

**Comment by firasm** [comment]
here's a fit to a single voxel: 
![unknown](https://cloud.githubusercontent.com/assets/2507459/8274482/a775606e-1847-11e5-9e73-ab5e63fcfd23.png)

This is the average of the region bounded by the red dots:

![unknown-1](https://cloud.githubusercontent.com/assets/2507459/8274487/b91cb2d6-1847-11e5-980d-435d796c227c.png)

Let me fit voxel by voxel and see what happens...

**Comment by DrSAR** [comment]
looking good - I'd say the the average is less clear than the single pixel fit.

**Comment by firasm** [comment]
I’d agree - I saw show the single voxel spectrum and fit. I tried fitting it voxel by voxel, and it’s a bit of a mess...

**Comment by DrSAR** [comment]
might depend on which parameters you fix and which you let roam...
