### ISSUE TITLE
The first Mouse brain with good CEST contrast...

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#47]
Yesterday @andrewcyung emailed an image of the first successful scan that exhibited CEST spectra. We've been trying to reproduce this effect size in all of our subsequent imaging sessions.

![screen shot 2015-06-21 at 8 40 06 pm](https://cloud.githubusercontent.com/assets/2507459/8275217/bfb5726e-1855-11e5-8023-22a727043861.png)

I decided to have a closer look at this scan, and it turns out that it isn't as great as we thought.

![unknown-2](https://cloud.githubusercontent.com/assets/2507459/8275190/4904f9c8-1855-11e5-88bf-9ad8edba299e.png)

Firstly, this effect isn't actually representative. For instance, this example just two pixels away doesn't show 3 peaks nearly as well as that one. 

![unknown-5](https://cloud.githubusercontent.com/assets/2507459/8275202/9351b872-1855-11e5-840e-4b989cc5706a.png)

Second, here's a fit of the data ; as you can see, peak size is very comparable to that in issue #46 with the EPI scan.
![unknown-3](https://cloud.githubusercontent.com/assets/2507459/8275192/5574a8c0-1855-11e5-99d3-be5e79c169ec.png)

Third, that peak at -3.5 ppm is very strange ...

Fourth, our shim on this day wasn't that good and the "good" pixel is right in the middle of the bad shim region. Here is a map of the water shift (in ppm)

![unknown-4](https://cloud.githubusercontent.com/assets/2507459/8275197/76be3e2e-1855-11e5-87e8-4d0102a439e8.png)

**Comment by andrewcyung** [comment]
I agree that the example spectrum wasn’t representative of its local region.  But I would at least say that the data looks convincing in this particular pixel.  The fact that it doesn’t vary smoothly over space has also made me question what we should actually expect in the spatial distribution.  Perhaps the spatial distribution of these chemicals really is limited to localized hotspots, and not smoothly varying regions?

For your fit, it looks like you didn’t try to fit the peak at 3.5 ppm.  If not, why not?

-andrew

**Comment by firasm** [comment]
I didn't fit the fourth peak because I figured it would be too many free parameters. I know this isn't the right thing to do, but at the moment all the fit parameters are free (peak location, amplitude, line width) for each peak.

here is the fit (that clearly is over determined):

![unknown-6](https://cloud.githubusercontent.com/assets/2507459/8286985/c12c7ac2-18c1-11e5-8ea6-b6c9156e6c3c.png)
