### ISSUE TITLE
dCEST_brain.wk2 - Mouse Brain EPI (2015-06-24)

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#50]
Here are the maps for the scans done on June 24th...

scans_of_interest['EPI_4s_water']=8
scans_of_interest['EPI_4s_1uT']=9
scans_of_interest['EPI_4s_3avg']=10
scans_of_interest['EPI_5s_1uT']=11
scans_of_interest['EPI_0.5s_4avg']=12 #(TR=1s down from 4s)
scans_of_interest['EPI_0.5s_8avg']=13
scans_of_interest['EPI_7s_1uT']=14
scans_of_interest['EPI_10s_1us']=15
scans_of_interest['EPI_5s_1uT_sl2']=16
scans_of_interest['EPI_5s_1uT_sl3']=17

## 2.5 ppm peak
![2_4 ppm](https://cloud.githubusercontent.com/assets/2507459/8412934/ecf88ce2-1e41-11e5-9ffd-d6620b39be71.png)

## 3.4 ppm peak

![3_4 ppm](https://cloud.githubusercontent.com/assets/2507459/8412949/02174a78-1e42-11e5-9e17-9e84ee0e9139.png)

**Comment by DrSAR** [comment]
these are nice - a look at a representative spectrum might be nice too

**Comment by firasm** [comment]
Here a spectrum with both peaks present...

![unknown-2](https://cloud.githubusercontent.com/assets/2507459/8413474/8e5ec530-1e45-11e5-8ff0-5c0030ccc3ed.png)

**Comment by DrSAR** [comment]
subtle. The delta-fit is the way to hide the hairy truth. I'd be a bit nervous to compare this over time or from group to group. Some sort of reliable reference would be nice. Maybe it;s sufficiently 'quantitative' as is but it's probably wise to have some scepticism with regards to that.
