### ISSUE TITLE
Setting variable spectral resolution for saturation offsets in CEST_EPI

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#54]
To accomplish this, @DrSAR and I think the best way to do this without breaking backward compatibility or spending hours working on this, is to allow the frequency offsets to be entered as a list (separated by commas).

That way, we can use our favourite software to generate exactly the list of offsets we want for a particular application, print the list, and then copy/paste it into Bruker.

I will hack a quick function to do this now, but this is an issue to handle the method programming side.

@DrSAR: Want to do this now ?

**Comment by firasm** [comment]
wrote a function, here is the input:

```
import cest.cest as cest
reload(cest)

dic = collections.OrderedDict([
                               ('dummy',[-60,60,10]),
                               ('start',[-5.1,5.1,0.1]),
                               ('baseline',[-60,60,10]),       
                               ('2.5',[2.5,3.0,0.01]),
                               ('3.4',[3.3,3.5,0.01])
                              ])

arr = cest.generate_offset_list(-5,5,0.1,dic)
```

here is the output:

[-60.0, -50.0, -40.0, -30.0, -20.0, -10.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0, -5.1, -5.0, -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4.0, -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3.0, -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2.0, -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1.0, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, -0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, -60.0, -50.0, -40.0, -30.0, -20.0, -10.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 2.5, 2.51, 2.52, 2.53, 2.54, 2.55, 2.56, 2.57, 2.58, 2.59, 2.6, 2.61, 2.62, 2.63, 2.64, 2.65, 2.66, 2.67, 2.68, 2.69, 2.7, 2.71, 2.72, 2.73, 2.74, 2.75, 2.76, 2.77, 2.78, 2.79, 2.8, 2.81, 2.82, 2.83, 2.84, 2.85, 2.86, 2.87, 2.88, 2.89, 2.9, 2.91, 2.92, 2.93, 2.94, 2.95, 2.96, 2.97, 2.98, 2.99, 3.3, 3.31, 3.32, 3.33, 3.34, 3.35, 3.36, 3.37, 3.38, 3.39, 3.4, 3.41, 3.42, 3.43, 3.44, 3.45, 3.46, 3.47, 3.48, 3.49, 3.5]

**Comment by andrewcyung** [comment]
It's the copy/paste into Bruker that will be a pain.  You might have to copy paste individual numbers.  Also remember that one line in the method editor can only display up to 64 values at a time.

I wonder if we could copy paste directly into the method file of each expno directory?  Would the method editor update with the new values if refreshed?

On Jul 6, 2015, at 11:15 AM, "firasm" <notifications@github.com<mailto:notifications@github.com>> wrote:


To accomplish this, @DrSAR<https://github.com/DrSAR> and I think the best way to do this without breaking backward compatibility or spending hours working on this, is to allow the frequency offsets to be entered as a list (separated by commas).

That way, we can use our favourite software to generate exactly the list of offsets we want for a particular application, print the list, and then copy/paste it into Bruker.

I will hack a quick function to do this now, but this is an issue to handle the method programming side.

@DrSAR<https://github.com/DrSAR>: Want to do this now ?

**Comment by DrSAR** [comment]
I think the hope is to copy into a string field and let the method handler parse the string rather than input individual numerical values.

For your second approach it sounds like macro programming would be the best route.

**Comment by firasm** [comment]
@DrSAR has finished coding the method, I will test it later this week (p.s. stefan is away from country starting next week).

I have also modified the function to generate the string offsets, and added features like alternating the frequencies and insertion of offset frequencies. 

Time to close this issue.
